wuip WiresharkFoundation.Wireshark 
wuip WinMerge.WinMerge 
wuip wethat.onenotetaggingkit 
wuip ScooterSoftware.BeyondCompare4 
wuip Postman.Postman.Canary 
wuip OpenJS.NodeJS 
wuip Notepad++.Notepad++ 
wuip Microsoft.WingetCreate 
wuip Microsoft.WindowsTerminal 
wuip Microsoft.WindowsSDK 
wuip Microsoft.WindowsAdminCenter 
wuip Microsoft.vott 
wuip Microsoft.VisualStudioCode.Insiders 
wuip Microsoft.VisualStudio.Locator 
wuip Microsoft.VisualStudio.2022.Community
wuip Microsoft.TeamMate 
wuip Microsoft.Sysinternals.ProcessExplorer 
wuip Microsoft.Sysinternals.ProcessMonitor 
wuip Microsoft.Sysinternals.Autoruns 
wuip Microsoft.Sqlcmd 
wuip Microsoft.PowerToys 
wuip Microsoft.PowerAutomateDesktop 
wuip Microsoft.PowerAppsCLI 
wuip Microsoft.OpenSSH.Beta 
wuip Microsoft.NuGet 
wuip Microsoft.MultilingualAppToolKit 
wuip Microsoft.Edge 
wuip Microsoft.DotNet.SDK.7 
wuip Microsoft.DotNet.SDK.6 
wuip Microsoft.DotNet.SDK.5 
wuip Microsoft.DotNet.SDK.3_1 
wuip Microsoft.DeploymentToolkit 
wuip Microsoft.BotFrameworkEmulator 
wuip Microsoft.BotFrameworkComposer 
wuip Microsoft.BingWallpaper 
wuip Microsoft.AzureDataStudio 
wuip mentebinaria.retoolkit 
wuip LINE.LINE 
wuip Kubernetes.minikube 
wuip JetBrains.Toolbox 
wuip jasongin.nvs 
wuip JanDeDobbeleer.OhMyPosh 
wuip HermannSchinagl.LinkShellExtension 
wuip Grammarly.Grammarly.Office 
wuip Grammarly.Grammarly 
wuip Google.Drive 
wuip GitHub.cli 
wuip GitExtensionsTeam.GitExtensions 
wuip Git.Git 
wuip Dropbox.Dropbox 
wuip Discord.Discord  
wuip CodeSector.TeraCopy      
wuip Canonical.Ubuntu              
wuip AgileBits.1Password           
wuip 7zip.7zip                               
wuip Microsoft.PowerShell

